//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scenes/PlayerCharacter/Settings/PlayerCharacterInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scenes/PlayerCharacter/Settings/PlayerCharacterInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerCharacterInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerCharacterInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerCharacterInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""9b48c267-9da4-4dbc-8348-1e76624395d7"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""393a7f49-1427-4a00-b6fb-4bd2c8b71b0a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHoldItem1"",
                    ""type"": ""Button"",
                    ""id"": ""025dd23c-3e14-4c65-b5cd-f2cb0a61919f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAltItem1"",
                    ""type"": ""Button"",
                    ""id"": ""66cad817-6a91-4c50-a07d-d9044d845e73"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem1"",
                    ""type"": ""Button"",
                    ""id"": ""8724d1b7-e241-4dac-95c5-b4fe50037197"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHoldItem2"",
                    ""type"": ""Button"",
                    ""id"": ""306a8763-ba3d-4d77-9e69-4b48a8e5cba7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAltItem2"",
                    ""type"": ""Button"",
                    ""id"": ""0612ff60-280c-4f54-9ce3-270ad2421a9a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem2"",
                    ""type"": ""Button"",
                    ""id"": ""0dd8754f-a355-4204-b81d-de7caa0a2559"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHoldItem3"",
                    ""type"": ""Button"",
                    ""id"": ""512bddb8-d156-4db4-86c1-0a3b09911481"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAltItem3"",
                    ""type"": ""Button"",
                    ""id"": ""e97a737b-cae2-4913-965d-ec2d94003a86"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem3"",
                    ""type"": ""Button"",
                    ""id"": ""c7789635-dd5b-47e8-a783-0920ef0736a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHoldHandRight"",
                    ""type"": ""Button"",
                    ""id"": ""d5ad794e-0b43-4cb7-b6ca-313f12a0cfa4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAltHandRight"",
                    ""type"": ""Button"",
                    ""id"": ""0fd1e426-1a23-45a8-a279-6fcea2930e47"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHandRight"",
                    ""type"": ""Button"",
                    ""id"": ""8b6a31e5-59ac-43f5-afe9-3136d0dde0d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHoldHandLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0447e6b0-1ffc-4b3c-9723-00bda5c1756f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseAltHandLeft"",
                    ""type"": ""Button"",
                    ""id"": ""78ff08da-f9c0-439f-8d2b-05af75590a90"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseHandLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b48897ea-bb96-4152-ba0a-04664519aac8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugKey"",
                    ""type"": ""Button"",
                    ""id"": ""9742020b-d4b8-4f54-8481-c10c0ca2b72b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8c82683b-af76-4e7c-a11c-e25ebaaeea4f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""390cc0ce-bc0e-4f0f-a07f-57c5b1c11645"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""20607b70-fee5-4aba-b87d-91f4f65af51f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0c3fc080-d4a6-4df6-93be-ea8a301a8ad3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""acdcf2b9-aef0-4269-b364-1689aced2b6f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5fec2dce-1ddd-41ef-9505-0b553d385b67"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHoldItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cc86ddc-24b5-4268-8279-1486679fcd52"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseAltItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4aa5149-a48f-4daa-9d93-19f95f92626e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""615a2eb1-2fd0-4c25-b734-9aadb4882c2a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHoldItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40bc8e2e-dc3f-47bb-8645-d143caee9bfe"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseAltItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b150ab98-f303-4043-aefa-b4ccf5856e5e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76b5eac3-6d5d-4e4d-9f18-a1f973e433b8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHoldItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6bafd47-ac51-450c-befc-b0fb3c291d71"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseAltItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6e6e55a-bc70-439b-b248-480d7fbf42c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87d6e4f9-720f-4d66-b7ed-51ad12e67c86"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHandRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32d81dc3-e6e8-4c15-959d-3b0a5d27d89f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHandLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dac4e8ae-3f9f-49ac-8935-2ac2fb55c0dc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseAltHandRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80305a7c-b9c5-4d6a-bb14-17274b735c29"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseAltHandLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42a028c3-b72c-47f9-88b1-065593ce0417"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7b1718-c3cd-4a9c-b392-fa87abccab81"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHoldHandRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1b47f59-3fc0-4687-ac51-d2d9f29fab48"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseHoldHandLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_UseHoldItem1 = m_Player.FindAction("UseHoldItem1", throwIfNotFound: true);
        m_Player_UseAltItem1 = m_Player.FindAction("UseAltItem1", throwIfNotFound: true);
        m_Player_UseItem1 = m_Player.FindAction("UseItem1", throwIfNotFound: true);
        m_Player_UseHoldItem2 = m_Player.FindAction("UseHoldItem2", throwIfNotFound: true);
        m_Player_UseAltItem2 = m_Player.FindAction("UseAltItem2", throwIfNotFound: true);
        m_Player_UseItem2 = m_Player.FindAction("UseItem2", throwIfNotFound: true);
        m_Player_UseHoldItem3 = m_Player.FindAction("UseHoldItem3", throwIfNotFound: true);
        m_Player_UseAltItem3 = m_Player.FindAction("UseAltItem3", throwIfNotFound: true);
        m_Player_UseItem3 = m_Player.FindAction("UseItem3", throwIfNotFound: true);
        m_Player_UseHoldHandRight = m_Player.FindAction("UseHoldHandRight", throwIfNotFound: true);
        m_Player_UseAltHandRight = m_Player.FindAction("UseAltHandRight", throwIfNotFound: true);
        m_Player_UseHandRight = m_Player.FindAction("UseHandRight", throwIfNotFound: true);
        m_Player_UseHoldHandLeft = m_Player.FindAction("UseHoldHandLeft", throwIfNotFound: true);
        m_Player_UseAltHandLeft = m_Player.FindAction("UseAltHandLeft", throwIfNotFound: true);
        m_Player_UseHandLeft = m_Player.FindAction("UseHandLeft", throwIfNotFound: true);
        m_Player_DebugKey = m_Player.FindAction("DebugKey", throwIfNotFound: true);
    }

    ~@PlayerCharacterInput()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerCharacterInput.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_UseHoldItem1;
    private readonly InputAction m_Player_UseAltItem1;
    private readonly InputAction m_Player_UseItem1;
    private readonly InputAction m_Player_UseHoldItem2;
    private readonly InputAction m_Player_UseAltItem2;
    private readonly InputAction m_Player_UseItem2;
    private readonly InputAction m_Player_UseHoldItem3;
    private readonly InputAction m_Player_UseAltItem3;
    private readonly InputAction m_Player_UseItem3;
    private readonly InputAction m_Player_UseHoldHandRight;
    private readonly InputAction m_Player_UseAltHandRight;
    private readonly InputAction m_Player_UseHandRight;
    private readonly InputAction m_Player_UseHoldHandLeft;
    private readonly InputAction m_Player_UseAltHandLeft;
    private readonly InputAction m_Player_UseHandLeft;
    private readonly InputAction m_Player_DebugKey;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @PlayerCharacterInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@PlayerCharacterInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Player_Move;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHoldItem1".
        /// </summary>
        public InputAction @UseHoldItem1 => m_Wrapper.m_Player_UseHoldItem1;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseAltItem1".
        /// </summary>
        public InputAction @UseAltItem1 => m_Wrapper.m_Player_UseAltItem1;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseItem1".
        /// </summary>
        public InputAction @UseItem1 => m_Wrapper.m_Player_UseItem1;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHoldItem2".
        /// </summary>
        public InputAction @UseHoldItem2 => m_Wrapper.m_Player_UseHoldItem2;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseAltItem2".
        /// </summary>
        public InputAction @UseAltItem2 => m_Wrapper.m_Player_UseAltItem2;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseItem2".
        /// </summary>
        public InputAction @UseItem2 => m_Wrapper.m_Player_UseItem2;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHoldItem3".
        /// </summary>
        public InputAction @UseHoldItem3 => m_Wrapper.m_Player_UseHoldItem3;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseAltItem3".
        /// </summary>
        public InputAction @UseAltItem3 => m_Wrapper.m_Player_UseAltItem3;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseItem3".
        /// </summary>
        public InputAction @UseItem3 => m_Wrapper.m_Player_UseItem3;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHoldHandRight".
        /// </summary>
        public InputAction @UseHoldHandRight => m_Wrapper.m_Player_UseHoldHandRight;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseAltHandRight".
        /// </summary>
        public InputAction @UseAltHandRight => m_Wrapper.m_Player_UseAltHandRight;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHandRight".
        /// </summary>
        public InputAction @UseHandRight => m_Wrapper.m_Player_UseHandRight;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHoldHandLeft".
        /// </summary>
        public InputAction @UseHoldHandLeft => m_Wrapper.m_Player_UseHoldHandLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseAltHandLeft".
        /// </summary>
        public InputAction @UseAltHandLeft => m_Wrapper.m_Player_UseAltHandLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseHandLeft".
        /// </summary>
        public InputAction @UseHandLeft => m_Wrapper.m_Player_UseHandLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player/DebugKey".
        /// </summary>
        public InputAction @DebugKey => m_Wrapper.m_Player_DebugKey;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @UseHoldItem1.started += instance.OnUseHoldItem1;
            @UseHoldItem1.performed += instance.OnUseHoldItem1;
            @UseHoldItem1.canceled += instance.OnUseHoldItem1;
            @UseAltItem1.started += instance.OnUseAltItem1;
            @UseAltItem1.performed += instance.OnUseAltItem1;
            @UseAltItem1.canceled += instance.OnUseAltItem1;
            @UseItem1.started += instance.OnUseItem1;
            @UseItem1.performed += instance.OnUseItem1;
            @UseItem1.canceled += instance.OnUseItem1;
            @UseHoldItem2.started += instance.OnUseHoldItem2;
            @UseHoldItem2.performed += instance.OnUseHoldItem2;
            @UseHoldItem2.canceled += instance.OnUseHoldItem2;
            @UseAltItem2.started += instance.OnUseAltItem2;
            @UseAltItem2.performed += instance.OnUseAltItem2;
            @UseAltItem2.canceled += instance.OnUseAltItem2;
            @UseItem2.started += instance.OnUseItem2;
            @UseItem2.performed += instance.OnUseItem2;
            @UseItem2.canceled += instance.OnUseItem2;
            @UseHoldItem3.started += instance.OnUseHoldItem3;
            @UseHoldItem3.performed += instance.OnUseHoldItem3;
            @UseHoldItem3.canceled += instance.OnUseHoldItem3;
            @UseAltItem3.started += instance.OnUseAltItem3;
            @UseAltItem3.performed += instance.OnUseAltItem3;
            @UseAltItem3.canceled += instance.OnUseAltItem3;
            @UseItem3.started += instance.OnUseItem3;
            @UseItem3.performed += instance.OnUseItem3;
            @UseItem3.canceled += instance.OnUseItem3;
            @UseHoldHandRight.started += instance.OnUseHoldHandRight;
            @UseHoldHandRight.performed += instance.OnUseHoldHandRight;
            @UseHoldHandRight.canceled += instance.OnUseHoldHandRight;
            @UseAltHandRight.started += instance.OnUseAltHandRight;
            @UseAltHandRight.performed += instance.OnUseAltHandRight;
            @UseAltHandRight.canceled += instance.OnUseAltHandRight;
            @UseHandRight.started += instance.OnUseHandRight;
            @UseHandRight.performed += instance.OnUseHandRight;
            @UseHandRight.canceled += instance.OnUseHandRight;
            @UseHoldHandLeft.started += instance.OnUseHoldHandLeft;
            @UseHoldHandLeft.performed += instance.OnUseHoldHandLeft;
            @UseHoldHandLeft.canceled += instance.OnUseHoldHandLeft;
            @UseAltHandLeft.started += instance.OnUseAltHandLeft;
            @UseAltHandLeft.performed += instance.OnUseAltHandLeft;
            @UseAltHandLeft.canceled += instance.OnUseAltHandLeft;
            @UseHandLeft.started += instance.OnUseHandLeft;
            @UseHandLeft.performed += instance.OnUseHandLeft;
            @UseHandLeft.canceled += instance.OnUseHandLeft;
            @DebugKey.started += instance.OnDebugKey;
            @DebugKey.performed += instance.OnDebugKey;
            @DebugKey.canceled += instance.OnDebugKey;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @UseHoldItem1.started -= instance.OnUseHoldItem1;
            @UseHoldItem1.performed -= instance.OnUseHoldItem1;
            @UseHoldItem1.canceled -= instance.OnUseHoldItem1;
            @UseAltItem1.started -= instance.OnUseAltItem1;
            @UseAltItem1.performed -= instance.OnUseAltItem1;
            @UseAltItem1.canceled -= instance.OnUseAltItem1;
            @UseItem1.started -= instance.OnUseItem1;
            @UseItem1.performed -= instance.OnUseItem1;
            @UseItem1.canceled -= instance.OnUseItem1;
            @UseHoldItem2.started -= instance.OnUseHoldItem2;
            @UseHoldItem2.performed -= instance.OnUseHoldItem2;
            @UseHoldItem2.canceled -= instance.OnUseHoldItem2;
            @UseAltItem2.started -= instance.OnUseAltItem2;
            @UseAltItem2.performed -= instance.OnUseAltItem2;
            @UseAltItem2.canceled -= instance.OnUseAltItem2;
            @UseItem2.started -= instance.OnUseItem2;
            @UseItem2.performed -= instance.OnUseItem2;
            @UseItem2.canceled -= instance.OnUseItem2;
            @UseHoldItem3.started -= instance.OnUseHoldItem3;
            @UseHoldItem3.performed -= instance.OnUseHoldItem3;
            @UseHoldItem3.canceled -= instance.OnUseHoldItem3;
            @UseAltItem3.started -= instance.OnUseAltItem3;
            @UseAltItem3.performed -= instance.OnUseAltItem3;
            @UseAltItem3.canceled -= instance.OnUseAltItem3;
            @UseItem3.started -= instance.OnUseItem3;
            @UseItem3.performed -= instance.OnUseItem3;
            @UseItem3.canceled -= instance.OnUseItem3;
            @UseHoldHandRight.started -= instance.OnUseHoldHandRight;
            @UseHoldHandRight.performed -= instance.OnUseHoldHandRight;
            @UseHoldHandRight.canceled -= instance.OnUseHoldHandRight;
            @UseAltHandRight.started -= instance.OnUseAltHandRight;
            @UseAltHandRight.performed -= instance.OnUseAltHandRight;
            @UseAltHandRight.canceled -= instance.OnUseAltHandRight;
            @UseHandRight.started -= instance.OnUseHandRight;
            @UseHandRight.performed -= instance.OnUseHandRight;
            @UseHandRight.canceled -= instance.OnUseHandRight;
            @UseHoldHandLeft.started -= instance.OnUseHoldHandLeft;
            @UseHoldHandLeft.performed -= instance.OnUseHoldHandLeft;
            @UseHoldHandLeft.canceled -= instance.OnUseHoldHandLeft;
            @UseAltHandLeft.started -= instance.OnUseAltHandLeft;
            @UseAltHandLeft.performed -= instance.OnUseAltHandLeft;
            @UseAltHandLeft.canceled -= instance.OnUseAltHandLeft;
            @UseHandLeft.started -= instance.OnUseHandLeft;
            @UseHandLeft.performed -= instance.OnUseHandLeft;
            @UseHandLeft.canceled -= instance.OnUseHandLeft;
            @DebugKey.started -= instance.OnDebugKey;
            @DebugKey.performed -= instance.OnDebugKey;
            @DebugKey.canceled -= instance.OnDebugKey;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHoldItem1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHoldItem1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAltItem1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAltItem1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseItem1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseItem1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHoldItem2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHoldItem2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAltItem2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAltItem2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseItem2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseItem2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHoldItem3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHoldItem3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAltItem3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAltItem3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseItem3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseItem3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHoldHandRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHoldHandRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAltHandRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAltHandRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHandRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHandRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHoldHandLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHoldHandLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseAltHandLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseAltHandLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseHandLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseHandLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DebugKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDebugKey(InputAction.CallbackContext context);
    }
}
